sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fimperioli/docker-react-starter-ci -f Dockerfile.dev .
script:
  - docker run -e CI=true fimperioli/docker-react-starter-ci npm run test

