FROM node:alpine

# Create app directory
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./


CMD ["npm","run","start"]